language: java
jdk:
- openjdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test cobertura:cobertura
after_success:
  - mvn coveralls:report
cache:
  directories:
    - $HOME/.m2
