name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CI_NAME: "Github Actions"

    steps:
      - uses: actions/checkout@v2
      - name: Set branch name and PR number
        id: refs
        env:
          BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
          COVERALLS_SECRET: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          echo "::set-output name=branch_name::${BRANCH_NAME_OR_REF#refs/heads/}"
          echo "::set-output name=pr_number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
          echo "::set-output name=secret_present::$(test -n "$COVERALLS_SECRET"; echo $?)"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true

      - name: "Check: Test"
        run: mvn verify -Dmaven.javadoc.skip=true jacoco:report

      - name: "Check: Code Style"
        run: mvn checkstyle:check -Dmaven.javadoc.skip=true

      - name: "Check: Documentation"
        run: mvn javadoc:aggregate

      - name: "Report: Coverage via coveralls.io"
        if: ${{ steps.refs.outputs.secret_present }} > 0
        run: mvn coveralls:report --no-transfer-progress -DrepoToken=$COVERALLS_SECRET
        env:
          CI_BUILD_NUMBER: ${{ github.run_id }}
          CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
          CI_BRANCH: ${{ steps.refs.outputs.branch_name }}
          CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
          COVERALLS_SECRET: ${{ secrets.COVERALLS_REPO_TOKEN }}
